# Generated by Django 4.2.11 on 2025-10-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='is_booked',
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('movie', 'seat'), name='unique_booking_per_movie_seat'),
        ),
    ]
