# Generated by Django 4.2.11 on 2025-10-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_seat_is_booked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='showtime',
            field=models.DateTimeField(blank=True, help_text='Movie showtime', null=True),
        ),
    ]
